package main

var (
	COX_EVENT_FEED_CHANNEL_ID = "1068927561058488353"

	ALL_MONEY_RATES_EMOJI_ID   = "Emoji"
	TEN_X_MONEY_RATES_EMOJI_ID = "Emoji"
	ALL_DROP_RATES_EMOJI_ID    = "Emoji"
	TEN_X_DROP_RATES_EMOJI_ID  = "Emoji"
)
