when:
  - event: push
    branch: main
  - event: manual

steps:
  - name: Fetch and Initialize Credentials
    when:
      - event: push
        branch: main
      - event: manual
    image: registry.mist-project.app/mist-shared/alpine-ci:latest
    environment:
      OP_SERVICE_ACCOUNT_TOKEN:
        from_secret: OP_TOKEN
      OP_VAULT:
        from_secret: OP_VAULT
      TENANT_ACCOUNT_ID: "k5q7ysjcaiu3cnfyjx7gjyevai"

    commands:
      - chmod +x helpers/fetch_creds_op.sh
      - ./helpers/fetch_creds_op.sh

  - name: Install go and project deps and build latest binary and deploy
    when:
      - event: push
        branch: main
      - event: manual
    image: registry.mist-project.app/mist-shared/alpine-ci:latest
    environment:
      ANSIBLE_HOST_KEY_CHECKING: False
    commands:
      # Download Go tarball
      - wget https://go.dev/dl/go1.25.0.linux-amd64.tar.gz

      # Remove any existing Go installation
      - rm -rf /usr/local/go

      # Extract to /usr/local
      - tar -C /usr/local -xzf go1.25.0.linux-amd64.tar.gz

      # Export `go` bin
      - export PATH="/usr/local/go/bin:$PATH"

      # Install project dependencies
      - go mod download

      # Create directory
      - mkdir -p /tmp/cox-bin/

      # Add ENV file
      - cp .tmpenvs /tmp/cox-bin/.env

      # Compile code into binary
      - go build -o /tmp/cox-bin/cox-event-listener src/main.go

      # Run playbook
      - ls /tmp/cox-bin/
      - |
        ansible-playbook -i ansible/inventory/hosts.ini \
          ansible/playbooks/deploy.yml \
          --extra-vars "ansible_ssh_private_key_file=key.pem" \
          --extra-vars "ansible_user=$TENANT_USERNAME" \
